# Конфигурация торговых стратегий T-Bank
# Трейдинг боты из открытых репозиториев GitHub

strategies:

  # 1. Python TrendBot - SMA Cross RSI стратегия
  trendbot_sma_rsi:
    module: "strategies.trendbot"
    class: "SMACrossRSIStrategy"
    description: "SMA Cross RSI Strategy from TrendBot"
    params:
      fast_sma: 50
      slow_sma: 200
      rsi_period: 14
      rsi_threshold: 30
      rsi_overbought: 70
      rsi_oversold: 30
    enabled: true

  # 2. NeuroInvest - LSTM Trend Following стратегия
  neuroinvest_lstm:
    module: "strategies.neuroinvest"
    class: "LSTMTrendFollowingStrategy"
    description: "LSTM Trend Following Strategy with ATR"
    params:
      model_type: "LSTM"
      lookback_window: 60
      atr_period: 14
      atr_multiplier: 1.5
      forecast_period: 5
      confidence_threshold: 0.7
    enabled: true

  # 3. OpexBot - Options Iron Condor стратегия
  opexbot_ironcondor:
    module: "strategies.opexbot"
    class: "IronCondorStrategy"
    description: "Options Iron Condor Strategy"
    params:
      underlying_tickers:
        - "SBERF"
        - "Si"
        - "GAZPF"
      strike_offset: 0.05
      expiry_days: 7
      buy_back_threshold: 0.5
      max_positions: 5
      risk_per_trade: 0.02
    enabled: true

# Общие настройки стратегий
common:
  backtest_period_days: 365
  risk_management:
    max_drawdown: 0.1
    max_positions: 3
    stop_loss_pct: 0.02
    take_profit_pct: 0.04

# Настройки логирования
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Настройки тестирования
testing:
  unit_tests: true
  backtest_period: "2025-02-01 to 2025-08-31"
  report_format: "json"
  performance_metrics: true

# Настройки AI интеграции
ai_integration:
  enabled: true
  model_types: ["LSTM", "CNN", "GradientBoosting"]
  retraining_interval_days: 7
  confidence_threshold: 0.8
  feature_engineering: true